env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - prettier
rules: { "prettier/prettier": ["error"] }
settings:
  react:
    version: detect
ignorePatterns:
  - /node_modules
  - tsconfig.json
  - setupTests.ts
  - reportWebVitals.ts
  - react-app-env.d.ts
